// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysProductPriceLookupDao is internal type for wrapping internal DAO implements.
type internalSysProductPriceLookupDao = *internal.SysProductPriceLookupDao

// sysProductPriceLookupDao is the data access object for table sys_product_price_lookup.
// You can define custom methods on it to extend its functionality as you wish.
type sysProductPriceLookupDao struct {
	internalSysProductPriceLookupDao
}

var (
	// SysProductPriceLookup is globally public accessible object for table sys_product_price_lookup operations.
	SysProductPriceLookup = sysProductPriceLookupDao{
		internal.NewSysProductPriceLookupDao(),
	}
)

// Fill with you ideas below.
