// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysAgentDao is internal type for wrapping internal DAO implements.
type internalSysAgentDao = *internal.SysAgentDao

// sysAgentDao is the data access object for table sys_agent.
// You can define custom methods on it to extend its functionality as you wish.
type sysAgentDao struct {
	internalSysAgentDao
}

var (
	// SysAgent is globally public accessible object for table sys_agent operations.
	SysAgent = sysAgentDao{
		internal.NewSysAgentDao(),
	}
)

// Fill with you ideas below.
