// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysTermsDao is internal type for wrapping internal DAO implements.
type internalSysTermsDao = *internal.SysTermsDao

// sysTermsDao is the data access object for table sys_terms.
// You can define custom methods on it to extend its functionality as you wish.
type sysTermsDao struct {
	internalSysTermsDao
}

var (
	// SysTerms is globally public accessible object for table sys_terms operations.
	SysTerms = sysTermsDao{
		internal.NewSysTermsDao(),
	}
)

// Fill with you ideas below.
