// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysProductVariationPriceDao is internal type for wrapping internal DAO implements.
type internalSysProductVariationPriceDao = *internal.SysProductVariationPriceDao

// sysProductVariationPriceDao is the data access object for table sys_product_variation_price.
// You can define custom methods on it to extend its functionality as you wish.
type sysProductVariationPriceDao struct {
	internalSysProductVariationPriceDao
}

var (
	// SysProductVariationPrice is globally public accessible object for table sys_product_variation_price operations.
	SysProductVariationPrice = sysProductVariationPriceDao{
		internal.NewSysProductVariationPriceDao(),
	}
)

// Fill with you ideas below.
