// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysBookingMetaDao is internal type for wrapping internal DAO implements.
type internalSysBookingMetaDao = *internal.SysBookingMetaDao

// sysBookingMetaDao is the data access object for table sys_booking_meta.
// You can define custom methods on it to extend its functionality as you wish.
type sysBookingMetaDao struct {
	internalSysBookingMetaDao
}

var (
	// SysBookingMeta is globally public accessible object for table sys_booking_meta operations.
	SysBookingMeta = sysBookingMetaDao{
		internal.NewSysBookingMetaDao(),
	}
)

// Fill with you ideas below.
