// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysProductVariationMetaDao is internal type for wrapping internal DAO implements.
type internalSysProductVariationMetaDao = *internal.SysProductVariationMetaDao

// sysProductVariationMetaDao is the data access object for table sys_product_variation_meta.
// You can define custom methods on it to extend its functionality as you wish.
type sysProductVariationMetaDao struct {
	internalSysProductVariationMetaDao
}

var (
	// SysProductVariationMeta is globally public accessible object for table sys_product_variation_meta operations.
	SysProductVariationMeta = sysProductVariationMetaDao{
		internal.NewSysProductVariationMetaDao(),
	}
)

// Fill with you ideas below.
