// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysPaymentTokenmetaDao is internal type for wrapping internal DAO implements.
type internalSysPaymentTokenmetaDao = *internal.SysPaymentTokenmetaDao

// sysPaymentTokenmetaDao is the data access object for table sys_payment_tokenmeta.
// You can define custom methods on it to extend its functionality as you wish.
type sysPaymentTokenmetaDao struct {
	internalSysPaymentTokenmetaDao
}

var (
	// SysPaymentTokenmeta is globally public accessible object for table sys_payment_tokenmeta operations.
	SysPaymentTokenmeta = sysPaymentTokenmetaDao{
		internal.NewSysPaymentTokenmetaDao(),
	}
)

// Fill with you ideas below.
