// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysProductMetaDao is internal type for wrapping internal DAO implements.
type internalSysProductMetaDao = *internal.SysProductMetaDao

// sysProductMetaDao is the data access object for table sys_product_meta.
// You can define custom methods on it to extend its functionality as you wish.
type sysProductMetaDao struct {
	internalSysProductMetaDao
}

var (
	// SysProductMeta is globally public accessible object for table sys_product_meta operations.
	SysProductMeta = sysProductMetaDao{
		internal.NewSysProductMetaDao(),
	}
)

// Fill with you ideas below.
