// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysVariationDao is internal type for wrapping internal DAO implements.
type internalSysVariationDao = *internal.SysVariationDao

// sysVariationDao is the data access object for table sys_variation.
// You can define custom methods on it to extend its functionality as you wish.
type sysVariationDao struct {
	internalSysVariationDao
}

var (
	// SysVariation is globally public accessible object for table sys_variation operations.
	SysVariation = sysVariationDao{
		internal.NewSysVariationDao(),
	}
)

// Fill with you ideas below.
