// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysProductLookupTermsDao is internal type for wrapping internal DAO implements.
type internalSysProductLookupTermsDao = *internal.SysProductLookupTermsDao

// sysProductLookupTermsDao is the data access object for table sys_product_lookup_terms.
// You can define custom methods on it to extend its functionality as you wish.
type sysProductLookupTermsDao struct {
	internalSysProductLookupTermsDao
}

var (
	// SysProductLookupTerms is globally public accessible object for table sys_product_lookup_terms operations.
	SysProductLookupTerms = sysProductLookupTermsDao{
		internal.NewSysProductLookupTermsDao(),
	}
)

// Fill with you ideas below.
