// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysProductAttributeDao is internal type for wrapping internal DAO implements.
type internalSysProductAttributeDao = *internal.SysProductAttributeDao

// sysProductAttributeDao is the data access object for table sys_product_attribute.
// You can define custom methods on it to extend its functionality as you wish.
type sysProductAttributeDao struct {
	internalSysProductAttributeDao
}

var (
	// SysProductAttribute is globally public accessible object for table sys_product_attribute operations.
	SysProductAttribute = sysProductAttributeDao{
		internal.NewSysProductAttributeDao(),
	}
)

// Fill with you ideas below.
