// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysVariationPriceDao is internal type for wrapping internal DAO implements.
type internalSysVariationPriceDao = *internal.SysVariationPriceDao

// sysVariationPriceDao is the data access object for table sys_variation_price.
// You can define custom methods on it to extend its functionality as you wish.
type sysVariationPriceDao struct {
	internalSysVariationPriceDao
}

var (
	// SysVariationPrice is globally public accessible object for table sys_variation_price operations.
	SysVariationPrice = sysVariationPriceDao{
		internal.NewSysVariationPriceDao(),
	}
)

// Fill with you ideas below.
