// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysVariationLookupDao is internal type for wrapping internal DAO implements.
type internalSysVariationLookupDao = *internal.SysVariationLookupDao

// sysVariationLookupDao is the data access object for table sys_variation_lookup.
// You can define custom methods on it to extend its functionality as you wish.
type sysVariationLookupDao struct {
	internalSysVariationLookupDao
}

var (
	// SysVariationLookup is globally public accessible object for table sys_variation_lookup operations.
	SysVariationLookup = sysVariationLookupDao{
		internal.NewSysVariationLookupDao(),
	}
)

// Fill with you ideas below.
