// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysSupplierDao is internal type for wrapping internal DAO implements.
type internalSysSupplierDao = *internal.SysSupplierDao

// sysSupplierDao is the data access object for table sys_supplier.
// You can define custom methods on it to extend its functionality as you wish.
type sysSupplierDao struct {
	internalSysSupplierDao
}

var (
	// SysSupplier is globally public accessible object for table sys_supplier operations.
	SysSupplier = sysSupplierDao{
		internal.NewSysSupplierDao(),
	}
)

// Fill with you ideas below.
