// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysProductVariationDao is internal type for wrapping internal DAO implements.
type internalSysProductVariationDao = *internal.SysProductVariationDao

// sysProductVariationDao is the data access object for table sys_product_variation.
// You can define custom methods on it to extend its functionality as you wish.
type sysProductVariationDao struct {
	internalSysProductVariationDao
}

var (
	// SysProductVariation is globally public accessible object for table sys_product_variation operations.
	SysProductVariation = sysProductVariationDao{
		internal.NewSysProductVariationDao(),
	}
)

// Fill with you ideas below.
