// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysPaymentMetaDao is internal type for wrapping internal DAO implements.
type internalSysPaymentMetaDao = *internal.SysPaymentMetaDao

// sysPaymentMetaDao is the data access object for table sys_payment_meta.
// You can define custom methods on it to extend its functionality as you wish.
type sysPaymentMetaDao struct {
	internalSysPaymentMetaDao
}

var (
	// SysPaymentMeta is globally public accessible object for table sys_payment_meta operations.
	SysPaymentMeta = sysPaymentMetaDao{
		internal.NewSysPaymentMetaDao(),
	}
)

// Fill with you ideas below.
