// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysProductLookupDao is internal type for wrapping internal DAO implements.
type internalSysProductLookupDao = *internal.SysProductLookupDao

// sysProductLookupDao is the data access object for table sys_product_lookup.
// You can define custom methods on it to extend its functionality as you wish.
type sysProductLookupDao struct {
	internalSysProductLookupDao
}

var (
	// SysProductLookup is globally public accessible object for table sys_product_lookup operations.
	SysProductLookup = sysProductLookupDao{
		internal.NewSysProductLookupDao(),
	}
)

// Fill with you ideas below.
