// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysProductDao is internal type for wrapping internal DAO implements.
type internalSysProductDao = *internal.SysProductDao

// sysProductDao is the data access object for table sys_product.
// You can define custom methods on it to extend its functionality as you wish.
type sysProductDao struct {
	internalSysProductDao
}

var (
	// SysProduct is globally public accessible object for table sys_product operations.
	SysProduct = sysProductDao{
		internal.NewSysProductDao(),
	}
)

// Fill with you ideas below.
