// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysProductKeywordsDao is internal type for wrapping internal DAO implements.
type internalSysProductKeywordsDao = *internal.SysProductKeywordsDao

// sysProductKeywordsDao is the data access object for table sys_product_keywords.
// You can define custom methods on it to extend its functionality as you wish.
type sysProductKeywordsDao struct {
	internalSysProductKeywordsDao
}

var (
	// SysProductKeywords is globally public accessible object for table sys_product_keywords operations.
	SysProductKeywords = sysProductKeywordsDao{
		internal.NewSysProductKeywordsDao(),
	}
)

// Fill with you ideas below.
