// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysPaymentTokensDao is internal type for wrapping internal DAO implements.
type internalSysPaymentTokensDao = *internal.SysPaymentTokensDao

// sysPaymentTokensDao is the data access object for table sys_payment_tokens.
// You can define custom methods on it to extend its functionality as you wish.
type sysPaymentTokensDao struct {
	internalSysPaymentTokensDao
}

var (
	// SysPaymentTokens is globally public accessible object for table sys_payment_tokens operations.
	SysPaymentTokens = sysPaymentTokensDao{
		internal.NewSysPaymentTokensDao(),
	}
)

// Fill with you ideas below.
