// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ugodubai-server/internal/app/system/dao/internal"
)

// internalSysPaymentDao is internal type for wrapping internal DAO implements.
type internalSysPaymentDao = *internal.SysPaymentDao

// sysPaymentDao is the data access object for table sys_payment.
// You can define custom methods on it to extend its functionality as you wish.
type sysPaymentDao struct {
	internalSysPaymentDao
}

var (
	// SysPayment is globally public accessible object for table sys_payment operations.
	SysPayment = sysPaymentDao{
		internal.NewSysPaymentDao(),
	}
)

// Fill with you ideas below.
