# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:123456@tcp(192.168.70.3:49168)/ugo"
        tables:          ""
        tablesEx:        "casbin_rule,sys_config,sys_dict_data,sys_dict_type"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/system"