// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "ugodubai-server/internal/app/common/logic/cache"
	_ "ugodubai-server/internal/app/common/logic/captcha"
	_ "ugodubai-server/internal/app/common/logic/middleware"
	_ "ugodubai-server/internal/app/common/logic/sysConfig"
	_ "ugodubai-server/internal/app/common/logic/sysDictData"
	_ "ugodubai-server/internal/app/common/logic/sysDictType"
)
